name: diffusion_all_ctspine_2e-4
diffusion: GaussianDiffusion
denoising_fn: Unet3D


vqgan_ckpt: '/home/user/Desktop/tomoray/best_checkpoint-epoch=64-val/recon_loss=0.04.ckpt'
diffusion_img_size: 64
diffusion_depth_size: 64
diffusion_num_channels: 8

vol_size_mm: [400, 400, 400]
det_size_mm: 400


dim_mults: [1, 2, 4, 8]


batch_size: 4
train_lr: 2e-4            
train_num_steps: 150000
gradient_accumulate_every: 2
ema_decay: 0.995
amp: False


timesteps: 1000
sampling_timesteps: 250
loss_type: l2
objective: pred_noise
cond_scale: 2.0


results_folder: './results'
results_folder_postfix: 'diffusion_experiment'
load_milestone: -1 
save_and_sample_every: 1000

num_workers: 10
gpus: 0
logger: tensorboard
